spring:
  application:
    name: service-discovery
  boot:
    admin:
      context-path: admin

server:
    port: 8761

eureka:
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false

