# Use a imagem base do Schema Registry da Confluent
FROM confluentinc/cp-schema-registry:5.4.0

ENV SCHEMA_REGISTRY_HOST_NAME "schema-registry.railway.internal"
ENV SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL "zookeeper.railway.internal:2181"

EXPOSE 8081

