spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  boot:
    admin:
      client:
        url: https://service-discovery.up.railway.app/admin


eureka:
  instance:
    hostname: https://prospect-leads-product-service.up.railway.app
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://service-discovery.up.railway.app/eureka/