spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}

eureka:
  client:
    enabled: true
    register-with-eureka: true
    eureka-server-d-n-s-name: service-discovery.up.railway.app