spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}

eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url: prospect-leads-system-production-c7cc.up.railway.app/eureka