server:
  port: 8080

spring:
  application:
    name: product-service
  main:
    allow-bean-definition-overriding: true
  sleuth:
    enabled: true
    trace-id128: true
    opentracing:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: ${spring.application.name}
      auto-commit: true
      idle-timeout: 10000
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 30000
      data-source-properties:
        useServerPrepStmts: true
        cachePrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

eureka:
  client:
    enabled: true
    register-with-eureka: true
