spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}

eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url:
      default-zone: service-discovery.up.railway.app