spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  boot:
    admin:
      client:
        url: http://service-discovery.railway.internal:8761/admin
        instance:
          management-base-url: http://service-discovery.railway.internal:8761/admin
          service-url: http://service-discovery.railway.internal:8761/admin

eureka:
  instance:
    hostname: prospect-leads-product-service.up.railway.app
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 30
  client:
    enabled: true
    register-with-eureka: true
    eureka-server-connect-timeout-seconds: 15
    eureka-server-read-timeout-seconds: 15
    serviceUrl:
      defaultZone: http://service-discovery.railway.internal:8761/eureka/