spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  boot:
    admin:
      client:
        url: https://service-discovery.up.railway.app/admin/

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://service-discovery.up.railway.app/eureka/