spring:
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    properties:
      schema.registry.url: mock://http://localhost:8081
  mail:
    host: xxx
    port: 587
    username: xxxx@xxx.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    enabled: false
    register-with-eureka: false

webservice:
  quotes:
    url: http://localhost:5000/insurance_quotes/v1
  products:
    url: http://localhost:5000/products/v1