spring:
  cloud:
    aws:
      ses:
        enabled: true
        endpoint: http://localstack.railway.internal:4566
        region: sa-east-1
  kafka:
    bootstrap-servers: kafka.railway.internal:29092
    properties:
      schema.registry.url: http://schema-registry.railway.internal:8081
  boot:
    admin:
      client:
        url: https://service-discovery.up.railway.app/admin/
        instance:
          service-url: https://service-discovery.up.railway.app/admin/

eureka:
  instance:
    hostname: prospect-leads-notification-service.railway.internal
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://service-discovery.up.railway.app/eureka/

