spring:
  cloud:
    aws:
      ses:
        enabled: true
        endpoint: http://localhost:4566
        region: sa-east-1

cloud:
  aws:
    stack:
      enabled: false
    region:
      static: sa-east-1

eureka:
  client:
    enabled: false
    register-with-eureka: false

webservice:
  quotes:
    url: http://localhost:5000/insurance_quotes/v1
  products:
    url: http://localhost:5000/products/v1