spring:
  redis:
    username: ${REDISUSER}
    password: ${REDISPASSWORD}
    port: ${REDISPORT}
    host: ${REDISHOST}
    ssl: false
    lettuce:
      pool:
        enabled: true
  kafka:
    bootstrap-servers: kafka.railway.internal:9092
    properties:
      schema.registry.url: http://schema-registry.railway.internal:8081      

aws:
  dynamodb:
    endpoint: http://localhost:4566
    region: sa-east-1
    credentials:
      access-key: foo
      secret-key: bar

eureka:
  client:
    enabled: true
    register-with-eureka: true

webservice:
  quotes:
    url: http://localhost:8080/insurance_quotes/v1
  products:
    url: http://localhost:8080/products/v1