spring:
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: kafka.railway.internal:29092
    properties:
      schema.registry.url: http://schema-registry.railway.internal:8081
  boot:
    admin:
      client:
        url: http://service-discovery.railway.internal:8761/admin
        instance:
          management-base-url: http://service-discovery.railway.internal:8761/admin
          service-url: http://service-discovery.railway.internal:8761/admin

eureka:
  instance:
    hostname: notification-service.up.railway.app
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 30
  client:
    enabled: true
    register-with-eureka: true
    eureka-server-connect-timeout-seconds: 15
    eureka-server-read-timeout-seconds: 15
    serviceUrl:
      defaultZone: http://service-discovery.railway.internal:8761/eureka/

