server:
  port: 8085

spring:
  application:
    name: bff-service
  main:
    allow-bean-definition-overriding: true
  redis:
    client-name: ${spring.application.name}
    client-type: LETTUCE
    lettuce:
      pool:
        enabled: true
  sleuth:
    enabled: true
    trace-id128: true
    opentracing:
      enabled: true

redis:
  streams:
    key: event:leads
    deliveryTime: 180000

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

eureka:
  client:
    enabled: true
    register-with-eureka: true

logging:
  level:
    org:
      springframework:
        web:
          reactive:
            function:
              client:
                ExchangeFunctions: TRACE