spring:
  redis:
    username: ${REDISUSER}
    password: ${REDISPASSWORD}
    port: ${REDISPORT}
    host: ${REDISHOST}
    ssl: false
    lettuce:
      pool:
        enabled: true
  boot:
    admin:
      client:
        url: http://service-discovery.railway.internal:8761/admin
        instance:
          management-base-url: http://service-discovery.railway.internal:8761/admin
          service-url: http://service-discovery.railway.internal:8761/admin
  kafka:
    bootstrap-servers: kafka.railway.internal:29092
    properties:
      schema.registry.url: http://schema-registry.railway.internal:8081

eureka:
  instance:
    hostname: prospect-leads-lead-service.up.railway.app
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 30
  client:
    enabled: true
    register-with-eureka: true
    eureka-server-connect-timeout-seconds: 15
    eureka-server-read-timeout-seconds: 15
    serviceUrl:
      defaultZone: http://service-discovery.railway.internal:8761/eureka/

aws:
  dynamodb:
    endpoint: https://localstack-production.up.railway.app
    region: sa-east-1
    credentials:
      access-key: foo
      secret-key: bar

webservice:
  products:
    url: https://prospect-leads-product-service.up.railway.app/products/v1
  quotes:
    url: https://prospect-leads-quote-service.up.railway.app/insurance_quotes/v1