spring:
  redis:
    password: redis
    port: 6379
    host: localhost
    ssl: false
    jedis:
      pool:
        enabled: true

eureka:
  client:
    enabled: false
    register-with-eureka: false

webservice:
  quotes:
    url: http://localhost:8080/insurance_quotes/v1
  products:
    url: http://localhost:8080/products/v1