spring:
  redis:
    password: redis
    port: 6379
    host: localhost
    ssl: false
    jedis:
      pool:
        enabled: true

aws:
  dynamodb:
    endpoint: http://localhost:4566
    region: sa-east-1
    credentials:
      access-key: foo
      secret-key: bar

eureka:
  client:
    enabled: false
    register-with-eureka: false

webservice:
  products:
    url: http://localhost:8080/products/v1
  quotes:
    url: http://localhost:8083/insurance_quotes/v1
