spring:
  redis:
    username: ${REDISUSER}
    password: ${REDISPASSWORD}
    port: ${REDISPORT}
    host: ${REDISHOST}
    ssl: false
    lettuce:
      pool:
        enabled: true
  boot:
    admin:
      client:
        url: https://service-discovery.up.railway.app/admin/
        instance:
          service-url: https://service-discovery.up.railway.app/admin/
  kafka:
    bootstrap-servers: kafka.railway.internal:29092
    properties:
      schema.registry.url: http://schema-registry.railway.internal:8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://service-discovery.up.railway.app/eureka/

aws:
  dynamodb:
    endpoint: http://localstack.railway.internal:4566
    region: sa-east-1
    credentials:
      access-key: foo
      secret-key: bar

webservice:
  products:
    url: https://prospect-leads-product-service.up.railway.app/products/v1
  quotes:
    url: https://prospect-leads-quote-service.up.railway.app/insurance_quotes/v1