server:
  port: 8083

spring:
  application:
    name: quote-service
  main:
    allow-bean-definition-overriding: true

  sleuth:
    enabled: true
    trace-id128: true
    opentracing:
      enabled: true
  data:
    mongodb:
      authentication-database: admin
      uuid-representation: standard

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

eureka:
  client:
    enabled: true
    register-with-eureka: true

logging:
  level:
    org:
      springframework:
        web:
          reactive:
            function:
              client:
                ExchangeFunctions: TRACE