spring:
  data:
    mongodb:
      host: ${MONGOHOST}
      port: ${MONGOPORT}
      database: quotes
      username: ${MONGOUSER}
      password: ${MONGOPASSWORD}
  boot:
    admin:
      client:
        url: https://service-discovery.up.railway.app/admin/
        instance:
          service-url: https://service-discovery.up.railway.app/admin/

eureka:
  instance:
    hostname: prospect-leads-quote-service.railway.internal
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://service-discovery.up.railway.app/eureka/


webservice:
  products:
    url: https://prospect-leads-product-service.up.railway.app/products/v1