spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/quotes
      username: root
      password: mongodb

eureka:
  client:
    enabled: true
    register-with-eureka: true

webservice:
  products:
    url: http://localhost:8080/products/v1