spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: quotes
      username: root
      password: mongodb

eureka:
  client:
    enabled: false
    register-with-eureka: false

webservice:
  products:
    url: http://localhost:8080/products/v1