spring:
  data:
    mongodb:
      uri: mongodb://root:mongodb@localhost:27017/quotes?authSource=admin
      username: root
      password: mongodb

eureka:
  client:
    enabled: false
    register-with-eureka: false

webservice:
  products:
    url: http://localhost:8080/products/v1